-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 11:43:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siigobattlecali
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siigobattlecali
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siigobattlecali` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema siigobattlecali
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siigobattlecali
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siigobattlecali` DEFAULT CHARACTER SET utf8mb4 ;
USE `siigobattlecali` ;

-- -----------------------------------------------------
-- Table `siigobattlecali`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`matchs` (
  `id_match` INT NOT NULL AUTO_INCREMENT,
  `match_room` VARCHAR(45) NULL,
  PRIMARY KEY (`id_match`),
  UNIQUE INDEX `id_UNIQUE` (`id_match` ASC),
  UNIQUE INDEX `match_room_UNIQUE` (`match_room` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siigobattlecali`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siigobattlecali`.`match_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`match_details` (
  `id_match_detail` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NOT NULL,
  `player` BIGINT(20) UNSIGNED NOT NULL,
  `no_rounds` INT NULL,
  `player_winner` VARCHAR(45) NULL,
  `time_match` VARCHAR(45) NULL,
  PRIMARY KEY (`id_match_detail`),
  INDEX `fk_match_details_matchs_idx` (`id_match` ASC),
  INDEX `fk_match_details_users1_idx` (`player` ASC),
  CONSTRAINT `fk_match_details_matchs`
    FOREIGN KEY (`id_match`)
    REFERENCES `siigobattlecali`.`matchs` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_details_users1`
    FOREIGN KEY (`player`)
    REFERENCES `siigobattlecali`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siigobattlecali`.`card_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`card_category` (
  `idcard_category` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(45) NULL,
  PRIMARY KEY (`idcard_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siigobattlecali`.`card_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`card_details` (
  `id_card_detail` INT NOT NULL AUTO_INCREMENT,
  `healt` VARCHAR(45) NULL,
  `ability` VARCHAR(45) NULL,
  `power` VARCHAR(45) NULL,
  `speed` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id_card_detail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siigobattlecali`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`cards` (
  `id_card` INT NOT NULL AUTO_INCREMENT,
  `id_card_category` INT NOT NULL,
  `id_card_details` INT NOT NULL,
  PRIMARY KEY (`id_card`, `id_card_category`, `id_card_details`),
  INDEX `fk_cards_card_category1_idx` (`id_card_category` ASC),
  INDEX `fk_cards_card_details1_idx` (`id_card_details` ASC),
  CONSTRAINT `fk_cards_card_category1`
    FOREIGN KEY (`id_card_category`)
    REFERENCES `siigobattlecali`.`card_category` (`idcard_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_card_details1`
    FOREIGN KEY (`id_card_details`)
    REFERENCES `siigobattlecali`.`card_details` (`id_card_detail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `siigobattlecali` ;

-- -----------------------------------------------------
-- Table `siigobattlecali`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siigobattlecali`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
